apiVersion: v1
kind: Service

metadata:
  name: service deployment

spec:
  selector:
   app: apache web server

  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80

  port: 
    - port: 9090
      targetPort: 90

  port: 
    - port: 8181
      targetPort: 91