apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apache httpd server

spec:
  replicas: 4                                     # number of copy of pods to run 
  template:                                       # Specification each  of pods

    metadata:
      labels:
        app: apache web server

    spec:                                         # specition of container inside each pods
      containers:
        - name: httpd container
          image: httpd                            # Container 1
          ports:
            - containerPort: 80

        - name: apache container
          image: httpd                            # Container 2
          ports:        
            - containerPort: 90


        - name: database container
          image: httpd                            # Container 3
          ports:
            - containerPort: 91

