version: "3"
services:

  # Mysql container and their details
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password



  # wordpress container and their details
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
        WORDPRESS_DB_PASSWORD: password






