
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: my-deploymnent

spec:
  replicas: 3

  template:
    metadata:
      name: my-deployment-pod
      labels:
        app: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.0
          ports:
            - containerPort: 80

